# Cobweb API Settings
api:
  url: "http://localhost:4000" # Address where API is hosted
  auth: "" # Authorization 

# Name of the server (empty to use system env var)
server-name: "" 

# Series Settings
series:
  id: 1
  name: "Casual"
  service: "CASUAL"
  
