# Cobweb API settings
api:
  url: "http://localhost:4000" # Address where API is hosted
  key: "" # Authorization

# Name of the server (empty to use system env var)
server-name: ""

# Series id assigned to matches
series-id: 1

# Spider website page links (remove section to remove references)
web:
  match: "https://localhost:3000/matches/{matchId}"
  profile: "https://localhost:3000/{name}"

  
